apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Spring-boot
  annotations:
    github.com/project-slug: HieuTVSE63007/Spring-boot
spec:
  type: other
  lifecycle: unknown
  owner: backstage
